### ISSUE TITLE
Actualización en el servicio del webservice v1.3

### ISSUE THREAD

**Issue by TheSpectroMx** [phpcfdi/sat-estado-cfdi-soap#4]
A partir del 18 de diciembre de 2020 se actualiza el servicio de validación por medio del webservice en su versión 1.3 donde se agrega **"ValidacionEFOS"** el cual tendrá como resultado **"ValidacionEFOS=100"** (se encontró en listado EFOS) o **"ValidacionEFOS=200"** (No se encontró en listado EFOS)

**Comment by eclipxe13** [comment]
Gracias, por favor, seguir el progreso en https://github.com/phpcfdi/sat-estado-cfdi/issues/11
